### github-action-variable-04.yml

name: Test Github Actions variable-04
run-name: Run Github Actions inputs, outputs, needs
on:
  workflow_dispatch:
    inputs:
      name:
        description: '이름'
        required: true
        default: 'INPUT'

jobs:
  input-date:
    runs-on: ubuntu-latest
    steps:
      - name: print input data
        run: echo "Hello, ${{ github.event.inputs.name }}"
