### github-action-variable-03.yml

name: Test Gitbub Actions variable-03
run-name: Run Github Actions var, secret
on:
  workflow_dispatch

jobs:
  check-secrets-context:
    runs-on: ubuntu-letest
    steps:
      - name: "Hello, secrets_Test"
        run: echo "Hello, ${{ secrets.SECRET_TEST }}"
