### github-action-variable-03.yml

name: Test Gitbub Actions variable-03
run-name: Run Github Actions var, secret
on:
  workflow_dispatch

jobs:
  check-vars-context:
    runs-on: ubuntu-letest
    steps:
      - name: "Hello, Var_Test"
        run: echo "Hello, ${{ vars.VAR_TEST }}"
